version: "3.8"

services:
  app:
    image: ghcr.io/serbia70/meituanone:latest
    container_name: meituanone-${SHOP_CODE}
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "2"
    ports:
      - "${SHOP_PORT}:3000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - /dev/usb:/dev/usb
    tmpfs:
      - /tmp:size=32m
